# Generated by Django 5.1.2 on 2024-10-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('county', models.CharField(choices=[('001', 'Allegany County'), ('002', 'Anne Arundel County'), ('003', 'Baltimore County'), ('004', 'Calvert County'), ('005', 'Caroline County'), ('006', 'Carroll County'), ('007', 'Cecil County'), ('008', 'Charles County'), ('009', 'Dorchester County'), ('010', 'Frederick County'), ('011', 'Garrett County'), ('012', 'Harford County'), ('013', 'Howard County'), ('014', 'Kent County'), ('015', 'Montgomery County'), ('016', "Prince George's County"), ('017', "Queen Anne's County"), ('018', "St. Mary's County"), ('019', 'Somerset County'), ('020', 'Talbot County'), ('021', 'Washington County'), ('022', 'Wicomico County'), ('023', 'Worcester County'), ('030', 'Baltimore City')], max_length=3)),
                ('type', models.CharField(choices=[('ART', 'Artist/Crafts/Gift Shop'), ('BRB', 'Barber'), ('BAK', 'Baking Company'), ('CC', 'Child Care'), ('EDU', 'Educational Services/Tutoring'), ('SSL', 'Spa/Salon'), ('CFT', 'Crafts'), ('LAN', 'Landscaping'), ('MOV', 'Moving/Delivery'), ('PET', 'Pet Care/Products'), ('PIC', 'Photography'), ('REL', 'Real Estate/Rental/Leasing'), ('RTL', 'Retail/Trade'), ('SPT', 'Sports/Training/Fitness'), ('OTH', 'Other')], max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
